name = "devcongress-short-links"
main = "worker.ts"
compatibility_date = "2026-08-09"
workers_dev = false

[vars]
PUBLIC_APP_ORIGIN = "https://em.devcongress.org"
EMS_RESOLVER_ORIGIN = "https://em.devcongress.org"

[observability]
enabled = true
