name = "events-management"
main = "server/worker.ts"
compatibility_date = "2026-06-15"
compatibility_flags = ["nodejs_compat"]

[vars]
PUBLIC_APP_URL = "https://devcon-comm.pages.dev"
PUBLIC_FRONTEND_ORIGIN = "https://devcon-comm.pages.dev"

[observability]
enabled = true
