export const PUBLIC_EVENT_COLLECTION_LIMIT = 250;
export const PUBLIC_ARCHIVE_ITEM_COLLECTION_LIMIT = 500;
export const PUBLIC_EVENT_ARCHIVE_ITEM_LIMIT = 100;

export const PUBLIC_API_BROWSER_MAX_AGE_SECONDS = 60;
export const PUBLIC_API_EDGE_MAX_AGE_SECONDS = 300;
export const PUBLIC_API_STALE_WHILE_REVALIDATE_SECONDS = 600;

export const PUBLIC_API_CACHE_CONTROL = [
  'public',
  `max-age=${PUBLIC_API_BROWSER_MAX_AGE_SECONDS}`,
  `s-maxage=${PUBLIC_API_EDGE_MAX_AGE_SECONDS}`,
  `stale-while-revalidate=${PUBLIC_API_STALE_WHILE_REVALIDATE_SECONDS}`,
].join(', ');
